---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "presentation"
  name: "presentation"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "presentation"
  type: "LoadBalancer"

